services:
  mongodb:
    build:
      context: .                # Contexte = dossier contenant Dockerfile, entrypoint, etc.
      dockerfile: Dockerfile    # (optionnel si c’est déjà le nom “Dockerfile”)
    container_name: mongodb
    ports:
      - "27017:27017"           # MongoDB
      - "3307:3307"             # BI Connector (mongosqld)
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/"
      ME_CONFIG_MONGODB_AUTH_DATABASE: "admin"
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongodb

  data-import:
    build: ./data_import
    container_name: data-import
    depends_on:
      - mongodb
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env

  analysis:
    build: ./analysis
    container_name: analysis
    depends_on:
      - mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
    - ./requetes:/scripts
  mongo-queries:
    image: mongo:6
    container_name: mongo-queries
    depends_on:
      - mongodb
    volumes:
      - ./requetes:/scripts
    entrypoint: ["mongosh", "--host", "mongodb", "-u", "root", "-p", "secret", "--authenticationDatabase", "admin", "/scripts/requetes.js"]

volumes:
  mongodb_data:
    driver: local
